# Generated by Django 4.2.3 on 2023-08-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_created_at_review_time_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='time_edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='time_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
