# Generated by Django 4.2.3 on 2023-08-13 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_time_edited_ticket_time_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='last_action',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_action',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
