# Generated by Django 4.2.3 on 2023-08-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_review_last_action_ticket_last_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='last_action',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='last_action',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
