# Generated by Django 4.2.3 on 2023-08-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_remove_review_last_action_remove_ticket_last_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='review_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='review_time_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
