# Generated by Django 4.2.3 on 2023-08-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_ticket_review_created_at_ticket_review_time_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='review_created_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='review_time_edited',
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.CharField(blank=True, max_length=8192),
        ),
        migrations.AlterField(
            model_name='review',
            name='headline',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.CharField(blank=True, max_length=8192),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
