# Generated by Django 4.2.3 on 2023-08-14 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_alter_review_body_alter_review_headline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='time_created',
            new_name='created_at',
        ),
    ]
