# Generated by Django 4.2.3 on 2023-08-16 12:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0013_rename_time_created_review_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollows',
            unique_together={('follower', 'followed_user')},
        ),
    ]
